// <auto-generated />
using System;
using Infraestrutura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestrutura.Migrations
{
    [DbContext(typeof(EmpresaContexto))]
    partial class EmpresaContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entidade.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdModalidade")
                        .HasColumnType("int");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("int");

                    b.Property<int?>("ModalidadeId")
                        .HasColumnType("int");

                    b.Property<bool>("Personal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModalidadeId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Aula");
                });

            modelBuilder.Entity("Dominio.Entidade.Aula_Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acesso")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int?>("AulaId")
                        .HasColumnType("int");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdAula")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("AulaId");

                    b.ToTable("Aula_Aluno");
                });

            modelBuilder.Entity("Dominio.Entidade.Entrada_Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("EntradasProduto");
                });

            modelBuilder.Entity("Dominio.Entidade.Eventos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LimiteAlunos")
                        .HasColumnType("int");

                    b.Property<string>("Poster")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Dominio.Entidade.Graduacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdModalidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdModalidade");

                    b.ToTable("Graduacoes", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidade.Inscricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EventoId")
                        .HasColumnType("int");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<bool>("Pagamento")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("Dominio.Entidade.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AulaExperimental")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdGraduacao")
                        .HasColumnType("int");

                    b.Property<int>("IdModalidade")
                        .HasColumnType("int");

                    b.Property<int>("IdPlano")
                        .HasColumnType("int");

                    b.Property<int>("IdVinculo")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("ValorAula")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdGraduacao");

                    b.HasIndex("IdModalidade");

                    b.HasIndex("IdPlano");

                    b.HasIndex("IdVinculo");

                    b.ToTable("Matriculas", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidade.Mensalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdMatricula")
                        .HasColumnType("int");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId");

                    b.ToTable("Mensalidades");
                });

            modelBuilder.Entity("Dominio.Entidade.Modalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProfessor")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdProfessor");

                    b.ToTable("Modalidades", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidade.Pagamento_Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdInscricao")
                        .HasColumnType("int");

                    b.Property<int>("InscricaoId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("InscricaoId");

                    b.ToTable("PagamentosEvento");
                });

            modelBuilder.Entity("Dominio.Entidade.Pagamento_Mensalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdMensalidade")
                        .HasColumnType("int");

                    b.Property<int>("MensalidadeId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("MensalidadeId");

                    b.ToTable("PagamentosMensalidade");
                });

            modelBuilder.Entity("Dominio.Entidade.Pagamento_Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdSaidaProduto")
                        .HasColumnType("int");

                    b.Property<int>("Saida_ProdutoId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Saida_ProdutoId");

                    b.ToTable("PagamentosProduto");
                });

            modelBuilder.Entity("Dominio.Entidade.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Dominio.Entidade.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Planos", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidade.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTamanho")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoProduto")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QtdeFinal")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("TamanhoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCredito")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorPix")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("TamanhoId");

                    b.HasIndex("TipoProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Dominio.Entidade.Saida_Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("SaidasProduto");
                });

            modelBuilder.Entity("Dominio.Entidade.Tamanho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Tamanhos");
                });

            modelBuilder.Entity("Dominio.Entidade.Tipo_Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("TiposProduto");
                });

            modelBuilder.Entity("Dominio.Entidade.Vinculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("ValorDesconto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Vinculos", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidade.Alunos", b =>
                {
                    b.HasBaseType("Dominio.Entidade.Pessoa");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidade.Professores", b =>
                {
                    b.HasBaseType("Dominio.Entidade.Pessoa");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Professores", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidade.Aula", b =>
                {
                    b.HasOne("Dominio.Entidade.Modalidade", "Modalidade")
                        .WithMany("Aulas")
                        .HasForeignKey("ModalidadeId");

                    b.HasOne("Dominio.Entidade.Professores", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId");

                    b.Navigation("Modalidade");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Dominio.Entidade.Aula_Aluno", b =>
                {
                    b.HasOne("Dominio.Entidade.Alunos", "Aluno")
                        .WithMany("Aula_Alunos")
                        .HasForeignKey("AlunoId");

                    b.HasOne("Dominio.Entidade.Aula", "Aula")
                        .WithMany("AulaAlunos")
                        .HasForeignKey("AulaId");

                    b.Navigation("Aluno");

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("Dominio.Entidade.Entrada_Produto", b =>
                {
                    b.HasOne("Dominio.Entidade.Produto", "Produto")
                        .WithMany("Entradas")
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Dominio.Entidade.Graduacao", b =>
                {
                    b.HasOne("Dominio.Entidade.Modalidade", "Modalidade")
                        .WithMany("Graduacoes")
                        .HasForeignKey("IdModalidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modalidade");
                });

            modelBuilder.Entity("Dominio.Entidade.Inscricao", b =>
                {
                    b.HasOne("Dominio.Entidade.Eventos", "Evento")
                        .WithMany("Inscricoes")
                        .HasForeignKey("EventoId");

                    b.HasOne("Dominio.Entidade.Pessoa", "Pessoa")
                        .WithMany("Inscricoes")
                        .HasForeignKey("PessoaId");

                    b.Navigation("Evento");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Dominio.Entidade.Matricula", b =>
                {
                    b.HasOne("Dominio.Entidade.Alunos", "Aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidade.Graduacao", "Graduacao")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdGraduacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidade.Modalidade", "Modalidade")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdModalidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidade.Plano", "Plano")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdPlano")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidade.Vinculo", "Vinculo")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdVinculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Graduacao");

                    b.Navigation("Modalidade");

                    b.Navigation("Plano");

                    b.Navigation("Vinculo");
                });

            modelBuilder.Entity("Dominio.Entidade.Mensalidade", b =>
                {
                    b.HasOne("Dominio.Entidade.Matricula", "Matricula")
                        .WithMany()
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("Dominio.Entidade.Modalidade", b =>
                {
                    b.HasOne("Dominio.Entidade.Professores", "Professor")
                        .WithMany("Modalidades")
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Dominio.Entidade.Pagamento_Evento", b =>
                {
                    b.HasOne("Dominio.Entidade.Inscricao", "Inscricao")
                        .WithMany()
                        .HasForeignKey("InscricaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscricao");
                });

            modelBuilder.Entity("Dominio.Entidade.Pagamento_Mensalidade", b =>
                {
                    b.HasOne("Dominio.Entidade.Mensalidade", "Mensalidade")
                        .WithMany("Pagamentos")
                        .HasForeignKey("MensalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensalidade");
                });

            modelBuilder.Entity("Dominio.Entidade.Pagamento_Produto", b =>
                {
                    b.HasOne("Dominio.Entidade.Saida_Produto", "Saida_Produto")
                        .WithMany()
                        .HasForeignKey("Saida_ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Saida_Produto");
                });

            modelBuilder.Entity("Dominio.Entidade.Produto", b =>
                {
                    b.HasOne("Dominio.Entidade.Tamanho", "Tamanho")
                        .WithMany("Produtos")
                        .HasForeignKey("TamanhoId");

                    b.HasOne("Dominio.Entidade.Tipo_Produto", "TipoProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("TipoProdutoId");

                    b.Navigation("Tamanho");

                    b.Navigation("TipoProduto");
                });

            modelBuilder.Entity("Dominio.Entidade.Saida_Produto", b =>
                {
                    b.HasOne("Dominio.Entidade.Pessoa", "Pessoa")
                        .WithMany("Saidas")
                        .HasForeignKey("PessoaId");

                    b.HasOne("Dominio.Entidade.Produto", "Produto")
                        .WithMany("Saidas")
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Pessoa");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Dominio.Entidade.Alunos", b =>
                {
                    b.HasOne("Dominio.Entidade.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Dominio.Entidade.Alunos", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entidade.Professores", b =>
                {
                    b.HasOne("Dominio.Entidade.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Dominio.Entidade.Professores", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entidade.Aula", b =>
                {
                    b.Navigation("AulaAlunos");
                });

            modelBuilder.Entity("Dominio.Entidade.Eventos", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("Dominio.Entidade.Graduacao", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("Dominio.Entidade.Mensalidade", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Dominio.Entidade.Modalidade", b =>
                {
                    b.Navigation("Aulas");

                    b.Navigation("Graduacoes");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("Dominio.Entidade.Pessoa", b =>
                {
                    b.Navigation("Inscricoes");

                    b.Navigation("Saidas");
                });

            modelBuilder.Entity("Dominio.Entidade.Plano", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("Dominio.Entidade.Produto", b =>
                {
                    b.Navigation("Entradas");

                    b.Navigation("Saidas");
                });

            modelBuilder.Entity("Dominio.Entidade.Tamanho", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Dominio.Entidade.Tipo_Produto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Dominio.Entidade.Vinculo", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("Dominio.Entidade.Alunos", b =>
                {
                    b.Navigation("Aula_Alunos");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("Dominio.Entidade.Professores", b =>
                {
                    b.Navigation("Modalidades");
                });
#pragma warning restore 612, 618
        }
    }
}
